stages:
  - install
  - lint
  - run-unit-test
  - buildAll-and-GenerateArtefacts
  - validate-framework
  - validation
  - ui-test
  - system-test
  - deploy
  - release

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - cat .gitlabmodules > .gitmodules
  - git submodule sync --recursive
  - git submodule update --init --recursive 

install:
  stage: install
  script:
    - bundle install
    - bin/bootstrap-if-needed
  dependencies: []
  cache:
    key: sdk-cache
    paths:
    - Carthage/
    - vendor/
  tags:
    - sdk

lint:
  stage: lint
  script:
    - bundle exec fastlane lint
  dependencies: []
  cache:
    key: sdk-cache
    paths:
    - Carthage/
    - vendor/
  artifacts:
    paths:
      - fastlane/swiftlint.html
  tags:
    - sdk
  allow_failure: false

run-unit-test:
  stage: run-unit-test
  script:
    - bundle exec fastlane runUnitTests
  dependencies: []
  cache:
    key: sdk-cache
    paths:
    - Carthage/
    - vendor/
    - derivedData/
  tags:
    - sdk

build:
  stage: buildAll-and-GenerateArtefacts
  script:
    - bundle exec fastlane buildAllAndGenerateArtefacts
  dependencies: []
  cache:
    key: sdk-cache
    paths:
    - Carthage/
    - vendor/
    - derivedData/
    - XcodeBuilds/
  artifacts:
    paths:
      - XcodeBuilds
  tags:
    - sdk
  only:
    - /^(release|develop|hotfix).*$/
    - master

validate-framework:
  stage: validate-framework
  script:
    - bundle exec fastlane validateFrameWork
  dependencies: []
  cache:
    key: sdk-cache
    paths:
    - Carthage/
    - vendor/
    - derivedData/
    - XcodeBuilds/
  tags:
    - sdk
  only:
    - /^(release|develop|hotfix).*$/
    - master

validation:
  stage: validation
  script:
    - bundle exec fastlane validateAll
  dependencies: []
  cache:
    key: sdk-cache
    paths:
    - Carthage/
    - vendor/
    - derivedData/
    - XcodeBuilds/
  tags:
    - sdk
  only:
    - master

ui-test:
  stage: ui-test
  script:
    - bundle exec fastlane uiTest
  dependencies: []
  cache:
    key: sdk-cache
    paths:
    - Carthage/
    - vendor/
    - derivedData/
    - XcodeBuilds/
  tags:
    - sdk
  except:
    - /task.*$/

system-test:
  stage: system-test
  script:
    - bundle exec fastlane systemTests
  dependencies: []
  cache:
    key: sdk-cache
    paths:
    - Carthage/
    - vendor/
    - derivedData/
    - XcodeBuilds/
  tags:
    - sdk
  only:
    - /^(release|develop|hotfix).*$/
    - master

trigger-test-app:
  stage: deploy
  script:
    - echo "Build internal testing app"
    - >
      curl -X POST
      -F token=$TOKEN_TRIGGER_INTERNAL_TEST_APP
      -F ref=develop
      -F "variables[SDK_PIPELINE_ID]=$CI_PIPELINE_IID"
      -F "variables[SDK_BRANCH]=$CI_BUILD_REF_NAME"
      https://gitlab.usabilla.net/api/v4/projects/146/trigger/pipeline
  cache:
    key: sdk-cache
    paths:
    - Carthage/
    - vendor/
    - derivedData/
    - XcodeBuilds/
  tags:
    - sdk
  except:
    - master
  
trigger-preview-app:
  stage: deploy
  script:
    - echo "Build Preview App"
    - >
      curl -X POST
      -F token=$TOKEN_TRIGGER_PREVIEW_APP
      -F ref=develop
      -F "variables[SDK_PIPELINE_ID]=$CI_PIPELINE_IID"
      -F "variables[SDK_BRANCH]=$CI_BUILD_REF_NAME"
      https://gitlab.usabilla.net/api/v4/projects/142/trigger/pipeline
  cache:
    key: sdk-cache
    paths:
    - Carthage/
    - vendor/
    - derivedData/
    - XcodeBuilds/
  tags:
    - sdk
  only:
    - /^(develop|hotfix|release).*$/
    
create-release-versions:
  stage: release
  script:
    - bundle exec fastlane createDraftRelease
  cache:
    key: sdk-cache
    paths:
    - Carthage/
    - vendor/
    - derivedData/
    - XcodeBuilds/
  tags:
    - sdk
  only:
    - release
  when: manual