coverage_service: cobertura_xml
xcodeproj: Usabilla.xcodeproj
workspace: Usabilla.xcworkspace
scheme: Usabilla
source_directory: .
output_directory: ./xml_report
ignore:
 - Usabilla/Utils/Reachability.swift
 - Usabilla/Utils/SwiftyJSON.swift
 - UsabillaTests/*
 - Usabilla/*ViewController.swift
 - Usabilla/*View.swift
 - Usabilla/*ViewCell.swift
 - Usabilla/*Component.swift

