excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - UsabillaTests
  - Usabilla/Utils/SwiftyJSON.swift 
  - Usabilla/Utils/StyleKit.swift 
  - Usabilla/Utils/Reachability.swift
  - Usabilla/Utils/SwiftEventBus.swift
  - UsabillaUITestApp
  - UsabillaExample.custom
  - UsabillaExample
  - codecov.swift
  - ReleaseValidator
opt_in_rules:
  - force_unwrapping

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
line_length: 300
function_body_length: 50

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
identifier_name:
  min_length: 
    warning: 3
    error: 3
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: # excluded via string array
    - id
    - URL
    - _
    - !str on
    - v


# No temp or asd

custom_rules:
  no_temp_allowed: # rule identifier
    included: ".*.swift" # regex that defines paths to include during linting. optional.
    name: "No Temp Allowed" # rule name. optional.
    regex: "([t,T][e]?mp[ ]+)" # matching pattern
    match_kinds: # SyntaxKinds to match. optional.
      - comment
      - identifier
    message: "Do not use temp." # violation message. optional.
    severity: error # violation severity. optional.
  no_temp_in_strings:
    regex: "([t,T][e]?mp[ ]+)"
    match_kinds: string

  no_asd_allowed: # rule identifier
    included: ".*.swift" # regex that defines paths to include during linting. optional.
    name: "No Asd Allowed" # rule name. optional.
    regex: "([a,A]sd)" # matching pattern
    match_kinds: # SyntaxKinds to match. optional.
      - comment
      - identifier
    message: "Do not use asd." # violation message. optional.
    severity: error # violation severity. optional.

  no_calls_to_usabilla: # rule identifier
    included: ".*.Usabilla\\/.*.swift" # regex that defines paths to include during linting. optional.    excluded: ".*Test\\.swift" # regex that defines paths to exclude during linting. optional
    name: "No calls to Usabilla class" # rule name. optional.
    regex: "Usabilla\\." # matching pattern
    match_kinds: # SyntaxKinds to match. optional.
      - identifier
    message: "Do not call the public interface." # violation message. optional.
    severity: error # violation severity. optional.

  no_open_or_public: # rule identifier
    included: ".*.Usabilla\\/.*.swift" # regex that defines paths to include during linting. optional.    excluded: ".*Test\\.swift" # regex that defines paths to exclude during linting. optional
    excluded: "(Usabilla.swift)|(UsabillaTheme.swift)|(Debug.swift)"
    name: "No open or public declaration" # rule name. optional.
    regex: "^\\s*(open)|(public)\\s+" # matching pattern
    message: "Do not use open or public declarations." # violation message. optional.
    severity: error # violation severity. optional.
